WITH ActualJPH AS (
    SELECT 
        REPLACE([section], 'Section ', '') AS section,
        'Actual JPH' AS general_process,

    ROUND(ISNULL(AVG(CASE WHEN [process] = 'UV-III' THEN [daily_result] ELSE NULL END), 0), 2) AS uv_iii,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Arc Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS arc_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Aluminum Coating UV II' THEN [daily_result] ELSE NULL END), 0), 2) AS aluminum_coating_uv_ii,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Servo Crimping' THEN [daily_result] ELSE NULL END), 0), 2) AS servo_crimping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ultrasonic Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS ultrasonic_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Cap Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS cap_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Primary Aluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_primary_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Secondary Aluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_secondary_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Airbag' THEN [daily_result] ELSE NULL END), 0), 2) AS airbag,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'A/B Sub PC' THEN [daily_result] ELSE NULL END), 0), 2) AS a_b_sub_pc,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Insertion to Connector' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_insertion_to_connector,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'V Type Twisting' THEN [daily_result] ELSE NULL END), 0), 2) AS v_type_twisting,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Primary' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_primary,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Secondary' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_secondary,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 2Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_2tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 4Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_4tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 5Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_5tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate ripping(UAS)Manual-NF-F' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_ripping_uas_manual_nf_f,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate ripping (UAS)Joint stripping(KB10)' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_ripping_uas_joint,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate stripping(KB10)' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_stripping_kb10,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate stripping(KB10)NSC/Weld' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_stripping_kb10_nsc_weld,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 2Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_2_tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 4Tons(PS-200)' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_4tons_ps_200,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 5Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_5tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Taping (Dispenser)' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_taping_dispenser,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Taping' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_taping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate Welding 0.13' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_welding_0_13,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding at Head' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_at_head,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding at Head 0.13' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_at_head_0_13,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Silicon Injection' THEN [daily_result] ELSE NULL END), 0), 2) AS silicon_injection,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding Cap Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_cap_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding Taping(13mm)' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_taping_13mm,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heatshrink' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink LA terminal' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_la_terminal,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Joint Crimping)' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_joint_crimping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Welding)' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Casting C385' THEN [daily_result] ELSE NULL END), 0), 2) AS casting_c385,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'STMAC Shieldwire(Nissan)' THEN [daily_result] ELSE NULL END), 0), 2) AS stmac_shieldwire_nissan,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Quick Stripping' THEN [daily_result] ELSE NULL END), 0), 2) AS quick_stripping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Heat Shrink(Blower)Sumitube' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_heat_shrink_blower_sumitube,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Drainwire Tip' THEN [daily_result] ELSE NULL END), 0), 2) AS drainwire_tip,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping Shieldwire' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_shieldwire,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 2TonsSW' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_2_tons_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Blue Taping(Dispenser)SW' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_blue_taping_dispenser_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Shieldwire Taping' THEN [daily_result] ELSE NULL END), 0), 2) AS shieldwire_taping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'HS Components Insertion SW' THEN [daily_result] ELSE NULL END), 0), 2) AS hs_components_insertion_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Joint Crimping)SW' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_joint_crimping_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Waterproof pad Press' THEN [daily_result] ELSE NULL END), 0), 2) AS waterproof_pad_press,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Low Viscosity' THEN [daily_result] ELSE NULL END), 0), 2) AS low_viscosity,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Air/Water leak test' THEN [daily_result] ELSE NULL END), 0), 2) AS air_water_leak_test,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'HIROSE' THEN [daily_result] ELSE NULL END), 0), 2) AS hirose,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Casting Battery' THEN [daily_result] ELSE NULL END), 0), 2) AS casting_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'STMACAluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS stmac_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 20Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_20tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Heat Shrink (Blower)Battery' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_heat_shrink_blower_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 20Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_20tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Dip Soldering (Battery)' THEN [daily_result] ELSE NULL END), 0), 2) AS dip_soldering_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ultrasonic Dip SolderingAluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS ultrasonic_dip_soldering_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'La molding' THEN [daily_result] ELSE NULL END), 0), 2) AS la_molding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Pressure Welding(Dome Lamp)' THEN [daily_result] ELSE NULL END), 0), 2) AS pressure_welding_dome_lamp,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ferrule Process' THEN [daily_result] ELSE NULL END), 0), 2) AS ferrule_process,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Gomusen Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS gomusen_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Point Marking' THEN [daily_result] ELSE NULL END), 0), 2) AS point_marking,

        ROUND(ISNULL(AVG(CASE 
                WHEN [process] IN (
                   'UV-III',
'Arc Welding',
'Aluminum Coating UV II',
'Servo Crimping',
'Ultrasonic Welding',
'Cap Insertion',
'Twisting Primary Aluminum',
'Twisting Secondary Aluminum',
'Airbag',
'A/B Sub PC',
'Manual Insertion to Connector',
'V Type Twisting',
'Twisting Primary',
'Twisting Secondary',
'Manual Crimping 2Tons',
'Manual Crimping 4Tons',
'Manual Crimping 5Tons',
'Intermediate ripping(UAS)Manual-NF-F',
'Intermediate ripping (UAS)Joint stripping(KB10)',
'Intermediate stripping(KB10)',
'Intermediate stripping(KB10)NSC/Weld',
'Joint Crimping 2Tons',
'Joint Crimping 4Tons(PS-200)',
'Joint Crimping 5Tons',
'Manual Taping (Dispenser)',
'Joint Taping',
'Intermediate Welding',
'Intermediate Welding 0.13',
'Welding at Head',
'Welding at Head 0.13',
'Silicon Injection',
'Welding Cap Insertion',
'Welding Taping(13mm)',
'Heatshrink',
'Heat Shrink LA terminal',
'Heat Shrink (Joint Crimping)',
'Heat Shrink (Welding)',
'Casting C385',
'STMAC Shieldwire(Nissan)',
'Quick Stripping',
'Manual Heat Shrink(Blower)Sumitube',
'Drainwire Tip',
'Manual Crimping Shieldwire',
'Joint Crimping 2TonsSW',
'Manual Blue Taping(Dispenser)SW',
'Shieldwire Taping',
'HS Components Insertion SW',
'Heat Shrink (Joint Crimping)SW',
'Waterproof pad Press',
'Low Viscosity',
'Air/Water leak test',
'HIROSE',
'Casting Battery',
'STMACAluminum',
'Manual Crimping 20Tons',
'Manual Heat Shrink (Blower)Battery',
'Joint Crimping 20Tons',
'Dip Soldering (Battery)',
'Ultrasonic Dip SolderingAluminum',
'La molding',
'Pressure Welding(Dome Lamp)',
'Ferrule Process',
'Gomusen Insertion',
'Point Marking'
                ) THEN [daily_result] 
                ELSE NULL 
            END), 0), 2) AS Total
    FROM 
        [secondary_dashboard_db].[dbo].[section_page]
    WHERE 
        [details] = 'Actual JPH'
        AND [process] IN (
           'UV-III',
'Arc Welding',
'Aluminum Coating UV II',
'Servo Crimping',
'Ultrasonic Welding',
'Cap Insertion',
'Twisting Primary Aluminum',
'Twisting Secondary Aluminum',
'Airbag',
'A/B Sub PC',
'Manual Insertion to Connector',
'V Type Twisting',
'Twisting Primary',
'Twisting Secondary',
'Manual Crimping 2Tons',
'Manual Crimping 4Tons',
'Manual Crimping 5Tons',
'Intermediate ripping(UAS)Manual-NF-F',
'Intermediate ripping (UAS)Joint stripping(KB10)',
'Intermediate stripping(KB10)',
'Intermediate stripping(KB10)NSC/Weld',
'Joint Crimping 2Tons',
'Joint Crimping 4Tons(PS-200)',
'Joint Crimping 5Tons',
'Manual Taping (Dispenser)',
'Joint Taping',
'Intermediate Welding',
'Intermediate Welding 0.13',
'Welding at Head',
'Welding at Head 0.13',
'Silicon Injection',
'Welding Cap Insertion',
'Welding Taping(13mm)',
'Heatshrink',
'Heat Shrink LA terminal',
'Heat Shrink (Joint Crimping)',
'Heat Shrink (Welding)',
'Casting C385',
'STMAC Shieldwire(Nissan)',
'Quick Stripping',
'Manual Heat Shrink(Blower)Sumitube',
'Drainwire Tip',
'Manual Crimping Shieldwire',
'Joint Crimping 2TonsSW',
'Manual Blue Taping(Dispenser)SW',
'Shieldwire Taping',
'HS Components Insertion SW',
'Heat Shrink (Joint Crimping)SW',
'Waterproof pad Press',
'Low Viscosity',
'Air/Water leak test',
'HIROSE',
'Casting Battery',
'STMACAluminum',
'Manual Crimping 20Tons',
'Manual Heat Shrink (Blower)Battery',
'Joint Crimping 20Tons',
'Dip Soldering (Battery)',
'Ultrasonic Dip SolderingAluminum',
'La molding',
'Pressure Welding(Dome Lamp)',
'Ferrule Process',
'Gomusen Insertion',
'Point Marking'
        )
    GROUP BY 
        [section]

    UNION ALL

    SELECT 
        'Overall' AS section,
        'Actual JPH' AS general_process,

ROUND(ISNULL(AVG(CASE WHEN [process] = 'UV-III' THEN [daily_result] ELSE NULL END), 0), 2) AS uv_iii,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Arc Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS arc_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Aluminum Coating UV II' THEN [daily_result] ELSE NULL END), 0), 2) AS aluminum_coating_uv_ii,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Servo Crimping' THEN [daily_result] ELSE NULL END), 0), 2) AS servo_crimping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ultrasonic Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS ultrasonic_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Cap Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS cap_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Primary Aluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_primary_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Secondary Aluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_secondary_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Airbag' THEN [daily_result] ELSE NULL END), 0), 2) AS airbag,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'A/B Sub PC' THEN [daily_result] ELSE NULL END), 0), 2) AS a_b_sub_pc,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Insertion to Connector' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_insertion_to_connector,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'V Type Twisting' THEN [daily_result] ELSE NULL END), 0), 2) AS v_type_twisting,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Primary' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_primary,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Twisting Secondary' THEN [daily_result] ELSE NULL END), 0), 2) AS twisting_secondary,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 2Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_2tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 4Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_4tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 5Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_5tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate ripping(UAS)Manual-NF-F' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_ripping_uas_manual_nf_f,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate ripping (UAS)Joint stripping(KB10)' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_ripping_uas_joint,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate stripping(KB10)' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_stripping_kb10,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate stripping(KB10)NSC/Weld' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_stripping_kb10_nsc_weld,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 2Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_2_tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 4Tons(PS-200)' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_4tons_ps_200,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 5Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_5tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Taping (Dispenser)' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_taping_dispenser,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Taping' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_taping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate Welding' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Intermediate Welding 0.13' THEN [daily_result] ELSE NULL END), 0), 2) AS intermediate_welding_0_13,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding at Head' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_at_head,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding at Head 0.13' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_at_head_0_13,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Silicon Injection' THEN [daily_result] ELSE NULL END), 0), 2) AS silicon_injection,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding Cap Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_cap_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Welding Taping(13mm)' THEN [daily_result] ELSE NULL END), 0), 2) AS welding_taping_13mm,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heatshrink' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink LA terminal' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_la_terminal,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Joint Crimping)' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_joint_crimping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Welding)' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_welding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Casting C385' THEN [daily_result] ELSE NULL END), 0), 2) AS casting_c385,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'STMAC Shieldwire(Nissan)' THEN [daily_result] ELSE NULL END), 0), 2) AS stmac_shieldwire_nissan,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Quick Stripping' THEN [daily_result] ELSE NULL END), 0), 2) AS quick_stripping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Heat Shrink(Blower)Sumitube' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_heat_shrink_blower_sumitube,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Drainwire Tip' THEN [daily_result] ELSE NULL END), 0), 2) AS drainwire_tip,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping Shieldwire' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_shieldwire,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 2TonsSW' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_2_tons_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Blue Taping(Dispenser)SW' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_blue_taping_dispenser_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Shieldwire Taping' THEN [daily_result] ELSE NULL END), 0), 2) AS shieldwire_taping,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'HS Components Insertion SW' THEN [daily_result] ELSE NULL END), 0), 2) AS hs_components_insertion_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Heat Shrink (Joint Crimping)SW' THEN [daily_result] ELSE NULL END), 0), 2) AS heat_shrink_joint_crimping_sw,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Waterproof pad Press' THEN [daily_result] ELSE NULL END), 0), 2) AS waterproof_pad_press,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Low Viscosity' THEN [daily_result] ELSE NULL END), 0), 2) AS low_viscosity,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Air/Water leak test' THEN [daily_result] ELSE NULL END), 0), 2) AS air_water_leak_test,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'HIROSE' THEN [daily_result] ELSE NULL END), 0), 2) AS hirose,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Casting Battery' THEN [daily_result] ELSE NULL END), 0), 2) AS casting_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'STMACAluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS stmac_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Crimping 20Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_crimping_20tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Manual Heat Shrink (Blower)Battery' THEN [daily_result] ELSE NULL END), 0), 2) AS manual_heat_shrink_blower_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Joint Crimping 20Tons' THEN [daily_result] ELSE NULL END), 0), 2) AS joint_crimping_20tons,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Dip Soldering (Battery)' THEN [daily_result] ELSE NULL END), 0), 2) AS dip_soldering_battery,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ultrasonic Dip SolderingAluminum' THEN [daily_result] ELSE NULL END), 0), 2) AS ultrasonic_dip_soldering_aluminum,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'La molding' THEN [daily_result] ELSE NULL END), 0), 2) AS la_molding,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Pressure Welding(Dome Lamp)' THEN [daily_result] ELSE NULL END), 0), 2) AS pressure_welding_dome_lamp,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Ferrule Process' THEN [daily_result] ELSE NULL END), 0), 2) AS ferrule_process,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Gomusen Insertion' THEN [daily_result] ELSE NULL END), 0), 2) AS gomusen_insertion,
ROUND(ISNULL(AVG(CASE WHEN [process] = 'Point Marking' THEN [daily_result] ELSE NULL END), 0), 2) AS point_marking


        ROUND(ISNULL(AVG(CASE 
                WHEN [process] IN (
                   'UV-III',
'Arc Welding',
'Aluminum Coating UV II',
'Servo Crimping',
'Ultrasonic Welding',
'Cap Insertion',
'Twisting Primary Aluminum',
'Twisting Secondary Aluminum',
'Airbag',
'A/B Sub PC',
'Manual Insertion to Connector',
'V Type Twisting',
'Twisting Primary',
'Twisting Secondary',
'Manual Crimping 2Tons',
'Manual Crimping 4Tons',
'Manual Crimping 5Tons',
'Intermediate ripping(UAS)Manual-NF-F',
'Intermediate ripping (UAS)Joint stripping(KB10)',
'Intermediate stripping(KB10)',
'Intermediate stripping(KB10)NSC/Weld',
'Joint Crimping 2Tons',
'Joint Crimping 4Tons(PS-200)',
'Joint Crimping 5Tons',
'Manual Taping (Dispenser)',
'Joint Taping',
'Intermediate Welding',
'Intermediate Welding 0.13',
'Welding at Head',
'Welding at Head 0.13',
'Silicon Injection',
'Welding Cap Insertion',
'Welding Taping(13mm)',
'Heatshrink',
'Heat Shrink LA terminal',
'Heat Shrink (Joint Crimping)',
'Heat Shrink (Welding)',
'Casting C385',
'STMAC Shieldwire(Nissan)',
'Quick Stripping',
'Manual Heat Shrink(Blower)Sumitube',
'Drainwire Tip',
'Manual Crimping Shieldwire',
'Joint Crimping 2TonsSW',
'Manual Blue Taping(Dispenser)SW',
'Shieldwire Taping',
'HS Components Insertion SW',
'Heat Shrink (Joint Crimping)SW',
'Waterproof pad Press',
'Low Viscosity',
'Air/Water leak test',
'HIROSE',
'Casting Battery',
'STMACAluminum',
'Manual Crimping 20Tons',
'Manual Heat Shrink (Blower)Battery',
'Joint Crimping 20Tons',
'Dip Soldering (Battery)',
'Ultrasonic Dip SolderingAluminum',
'La molding',
'Pressure Welding(Dome Lamp)',
'Ferrule Process',
'Gomusen Insertion',
'Point Marking'
                ) THEN [daily_result] 
                ELSE NULL 
            END), 0), 2) AS Total
    FROM 
        [secondary_dashboard_db].[dbo].[section_page]
    WHERE 
        [details] = 'Actual JPH'
        AND [process] IN (
           'UV-III',
'Arc Welding',
'Aluminum Coating UV II',
'Servo Crimping',
'Ultrasonic Welding',
'Cap Insertion',
'Twisting Primary Aluminum',
'Twisting Secondary Aluminum',
'Airbag',
'A/B Sub PC',
'Manual Insertion to Connector',
'V Type Twisting',
'Twisting Primary',
'Twisting Secondary',
'Manual Crimping 2Tons',
'Manual Crimping 4Tons',
'Manual Crimping 5Tons',
'Intermediate ripping(UAS)Manual-NF-F',
'Intermediate ripping (UAS)Joint stripping(KB10)',
'Intermediate stripping(KB10)',
'Intermediate stripping(KB10)NSC/Weld',
'Joint Crimping 2Tons',
'Joint Crimping 4Tons(PS-200)',
'Joint Crimping 5Tons',
'Manual Taping (Dispenser)',
'Joint Taping',
'Intermediate Welding',
'Intermediate Welding 0.13',
'Welding at Head',
'Welding at Head 0.13',
'Silicon Injection',
'Welding Cap Insertion',
'Welding Taping(13mm)',
'Heatshrink',
'Heat Shrink LA terminal',
'Heat Shrink (Joint Crimping)',
'Heat Shrink (Welding)',
'Casting C385',
'STMAC Shieldwire(Nissan)',
'Quick Stripping',
'Manual Heat Shrink(Blower)Sumitube',
'Drainwire Tip',
'Manual Crimping Shieldwire',
'Joint Crimping 2TonsSW',
'Manual Blue Taping(Dispenser)SW',
'Shieldwire Taping',
'HS Components Insertion SW',
'Heat Shrink (Joint Crimping)SW',
'Waterproof pad Press',
'Low Viscosity',
'Air/Water leak test',
'HIROSE',
'Casting Battery',
'STMACAluminum',
'Manual Crimping 20Tons',
'Manual Heat Shrink (Blower)Battery',
'Joint Crimping 20Tons',
'Dip Soldering (Battery)',
'Ultrasonic Dip SolderingAluminum',
'La molding',
'Pressure Welding(Dome Lamp)',
'Ferrule Process',
'Gomusen Insertion',
'Point Marking'
        )
),
Combined AS (
   SELECT * FROM ActualJPH
)
SELECT *
FROM Combined
ORDER BY 
    CASE section
        WHEN 'Overall' THEN 0
        WHEN '1' THEN 1
        WHEN '2' THEN 2
        WHEN '3' THEN 3
        WHEN '3.1' THEN 3.1
        WHEN '4' THEN 4  
        WHEN '5' THEN 5
        WHEN '6' THEN 6
        WHEN '7' THEN 7
        WHEN '8' THEN 8
        WHEN '9' THEN 9
        ELSE 10
    END,
    general_process DESC;
