<?php
header('Content-Type: text/csv');
header('Content-Disposition: attachment;filename=shot_count_export.csv');

include'conn.php'; // Make sure this connects to the right DB or has access to it

$output = fopen('php://output','w');

// CSV header row
fputcsv($output, ['Section','Car Model','Base Product','Block','Block 2','Product','Line No','UV-III 1', 
'UV-III 2', 
'UV-III 4', 
'UV-III 5', 
'UV-III 7', 
'UV-III 8', 
'Arc Welding', 
'Aluminum Coating UV-II', 
'Servo Crimping', 
'Ultrasonic Welding', 
'Cap Insertion', 
'Twisting Primary (Aluminum Short Wires) L=1~3000mm', 
'Twisting Primary (Aluminum Long Wires) L=3001mm~', 
'Twisting Secondary (Aluminum Short Wires) L=1~3000mm', 
'Twisting Secondary (Aluminum Long Wires)', 
'Airbag', 
'A/B Sub PC', 
'Manual Insertion to Connector', 
'V type twisting', 
'Twisting Primary (Normal Short Wires) L=1~3000mm', 
'Twisting Primary (Normal Long Wires) L=3001mm~', 
'Twisting Secondary (Normal Short Wires) L=1~3000mm', 
'Twisting Secondary (Normal Long Wires) L=3001mm~', 
'Manual Crimping 2Tons (with gomusen)', 
'Manual Crimping 2Tons (normal-single crimp)', 
'Manual Crimping 2Tons (normal-double crimp)', 
'Manual Crimping 2Tons (to be joint on SW)', 
'Manual Crimping 2Tons NSC/ Weld', 
'Manual Crimping 4Tons (normal terminal)', 
'Manual Crimping 4Tons (LA terminal)', 
'Manual Crimping (NF-F)', 
'Manual Crimping 5Tons', 
'Intermediate ripping (UAS) Manual-NF-F', 
'Intermediate ripping (UAS) Joint', 
'Intermediate stripping (KB10)', 
'Intermediate stripping (KB10) NSC/ Weld', 
'Joint Crimping 2Tons (PS-800)', 
'Joint Crimping 2Tons (PS-700)', 
'Joint Crimping 2Tons (PS-017/126)', 
'Joint Crimping 2Tons NSC/ Weld', 
'Joint Crimping 4Tons (PS-200)', 
'Joint Crimping 5Tons', 
'Manual Taping (Dispenser)', 
'Joint Taping (11mm)', 
'Joint Taping (12mm)', 
'Joint Taping (13mm)', 
'Joint Taping (13mm) NSC/ Weld', 
'Intermediate Welding (Electrode 1)', 
'Intermediate Welding (Electrode 2)', 
'Intermediate Welding (Electrode 3)', 
'Intermediate Welding (Electrode 4)', 
'Intermediate Welding (Electrode 5)', 
'Intermediate Welding 0.13 (Electrode 1)', 
'Intermediate Welding 0.13 (Electrode 2)', 
'Welding at Head (Electrode 1)', 
'Welding at Head (Electrode 2)', 
'Welding at Head (Electrode 3)', 
'Welding at Head (Electrode 4)', 
'Welding at Head (Electrode 5)', 
'Welding at Head 0.13 (Electrode 1)', 
'Welding at Head 0.13 (Electrode 2)', 
'Silicon Injection', 
'Welding Cap Insertion', 
'Welding Taping (13mm)', 
'HS Components Insertion', 
'Heat Shrink LA terminal', 
'Heat Shrink (Joint Crimping)', 
'Heat Shrink (Welding)', 
'Casting C385', 
'STMAC Shieldwire (Nissan)', 
'Quick Stripping 927 (Auto)', 
'Quick Stripping 311 (Manual)', 
'Manual Heat Shrink (Blower) Sumitube', 
'Drainwire Tip', 
'Manual Crimping Shieldwire 2T', 
'Manual Crimping Shieldwire 4T', 
'Joint Crimping 2Tons (PS-800/S-2) SW', 
'Joint Crimping 2Tons (PS-017/SS-2) SW', 
'Manual Blue Taping (Dispenser) SW', 
'Shieldwire Taping', 
'HS Components Insertion SW', 
'Heat Shrink (Joint Crimping) SW', 
'Waterproof pad Press - Joint', 
'Waterproof Pad Press - Weld', 
'Low Viscosity', 
'Air/Water leak test', 
'HIROSE (Sheath stripping) 927R', 
'HIROSE (Unistrip)', 
'HIROSE (Acetate Taping)', 
'HIROSE (Manual Crimping) 2 tons', 
'HIROSE (Copper taping)', 
'HIROSE (HGT17AP crimping)', 
'Casting C373', 
'Casting C377', 
'Casting C371', 
'STMAC Aluminum', 
'Manual Crimping 20Tons', 
'Manual Heat Shrink (Blower) Battery', 
'Joint Crimping 20Tons', 
'Dip Soldering (Battery)', 
'Ultrasonic Dip Soldering Aluminum', 
'LA molding', 
'Air/Water leak test', 
'Pressure Welding (Dome Lamp)', 
'Ferrule - Casting C373', 
'Ferrule - Parts Insertion', 
'Ferrule - Braided wire folding', 
'Outside ferrule insertion', 
'Ferrule - Manual Crimping 2T', 
'Ferrule Crimping', 
'Ferrule - Joint Crimping 2T', 
'Ferrule - Welding at head', 
'Ferrule - Welding Taping', 
'Gomusen Insertion', 
'Point Marking']);

// Query all data from the correct table
$sql = "SELECT section, car_model, base_product, block, block_2, product, line_no,
uv_iii_1, 
uv_iii_2,
uv_iii_4,
uv_iii_5,
uv_iii_7,
uv_iii_8,
arc_welding,
aluminum_coating_uv_ii,
servo_crimping,
ultrasonic_welding,
cap_insertion,
twisting_primary_aluminum_short_wires_l_1_3000mm,
twisting_primary_aluminum_long_wires_l_3001mm,
twisting_secondary_aluminum_short_wires_l_1_3000mm,
twisting_secondary_aluminum_long_wires_l_3001mm,
airbag,
a_b_sub_pc,
manual_insertion_to_connector,
v_type_twisting,
twisting_primary_normal_short_wires_l_1_3000mm,
twisting_primary_normal_long_wires_l_3001mm,
twisting_secondary_normal_short_wires_l_1_3000mm,
twisting_secondary_normal_long_wires_l_3001mm,
manual_crimping_2tons_with_gomusen,
manual_crimping_2tons_normal_single_crimp,
manual_crimping_2tons_normal_double_crimp,
manual_crimping_2tons_to_be_joint_on_sw,
manual_crimping_2tons_nsc_weld,
manual_crimping_4tons_normal_terminal,
manual_crimping_4tons_la_terminal,
manual_crimping_nf_f,
manual_crimping_5tons,
intermediate_ripping_uas_manual_nf_f,
intermediate_ripping_uas_joint,
intermediate_stripping_kb10,
intermediate_stripping_kb10_nsc_weld,
joint_crimping_2tons_ps_800,
joint_crimping_2tons_ps_700,
joint_crimping_2tons_ps_017_126,
joint_crimping_2tons_nsc_weld,
joint_crimping_4tons_ps_200,
joint_crimping_5tons,
manual_taping_dispenser,
joint_taping_11mm,
joint_taping_12mm,
joint_taping_13mm,
joint_taping_13mm_nsc_weld,
intermediate_welding_electrode_1,
intermediate_welding_electrode_2,
intermediate_welding_electrode_3,
intermediate_welding_electrode_4,
intermediate_welding_electrode_5,
intermediate_welding_0_13_electrode_1,
intermediate_welding_0_13_electrode_2,
welding_at_head_electrode_1,
welding_at_head_electrode_2,
welding_at_head_electrode_3,
welding_at_head_electrode_4,
welding_at_head_electrode_5,
welding_at_head_0_13_electrode_1,
welding_at_head_0_13_electrode_2,
silicon_injection,
welding_cap_insertion,
welding_taping_13mm,
hs_components_insertion,
heat_shrink_la_terminal,
heat_shrink_joint_crimping,
heat_shrink_welding,
casting_c385,
stmac_shieldwire_nissan,
quick_stripping_927_auto,
quick_stripping_311_manual,
manual_heat_shrink_blower_sumitube,
drainwire_tip,
manual_crimping_shieldwire_2t,
manual_crimping_shieldwire_4t,
joint_crimping_2tons_ps_800_s_2_sw,
joint_crimping_2tons_ps_017_ss_2_sw,
manual_blue_taping_dispenser_sw,
shieldwire_taping,
hs_components_insertion_sw,
heat_shrink_joint_crimping_sw,
waterproof_pad_press_joint,
waterproof_pad_press_weld,
low_viscosity,
air_water_leak_test,
hirose_sheath_stripping_927r,
hirose_unistrip,
hirose_acetate_taping,
hirose_manual_crimping_2_tons,
hirose_copper_taping,
hirose_hgt17ap_crimping,
casting_c373,
casting_c377,
casting_c371,
stmac_aluminum,
manual_crimping_20tons,
manual_heat_shrink_blower_battery,
joint_crimping_20tons,
dip_soldering_battery,
ultrasonic_dip_soldering_aluminum,
la_molding,
air_water_leak_test_2, 
pressure_welding_dome_lamp, 
ferrule_casting_c373,
ferrule_parts_insertion,
ferrule_braided_wire_folding,
outside_ferrule_insertion,
ferrule_manual_crimping_2t,
ferrule_crimping,
ferrule_joint_crimping_2t,
ferrule_welding_at_head,
ferrule_welding_taping,
gomusen_insertion,
point_marking

 FROM [secondary_dashboard_db].[dbo].[sp_shot_count]";
$result = sqlsrv_query($conn, $sql);

if ($result === false) {
    die(print_r(sqlsrv_errors(), true)); // Show error if query fails
}

// Loop through and write each row to the CSV
while ($row = sqlsrv_fetch_array($result, SQLSRV_FETCH_ASSOC)) {
    fputcsv($output, [
        $row['section'] ??'',
        $row['car_model'] ??'',
        $row['base_product'] ??'',
        $row['block'] ??'',
        $row['block_2'] ??'',
        $row['product'] ??'',
        $row['line_no'] ??'',
        $row['uv_iii_1'] ??'',
        $row['uv_iii_2'] ??'',
        $row['uv_iii_4'] ??'',
        $row['uv_iii_5'] ??'',
        $row['uv_iii_7'] ??'',
        $row['uv_iii_8'] ??'',
        $row['arc_welding'] ??'',
        $row['aluminum_coating_uv_ii'] ??'',
        $row['servo_crimping'] ??'',
        $row['ultrasonic_welding'] ??'',
        $row['cap_insertion'] ??'',
        $row['twisting_primary_aluminum_short_wires_l_1_3000mm'] ??'',
        $row['twisting_primary_aluminum_long_wires_l_3001mm'] ??'',
        $row['twisting_secondary_aluminum_short_wires_l_1_3000mm'] ??'',
        $row['twisting_secondary_aluminum_long_wires_l_3001mm'] ??'',
        $row['airbag'] ??'',
        $row['a_b_sub_pc'] ??'',
        $row['manual_insertion_to_connector'] ??'',
        $row['v_type_twisting'] ??'',
        $row['twisting_primary_normal_short_wires_l_1_3000mm'] ??'',
        $row['twisting_primary_normal_long_wires_l_3001mm'] ??'',
        $row['twisting_secondary_normal_short_wires_l_1_3000mm'] ??'',
        $row['twisting_secondary_normal_long_wires_l_3001mm'] ??'',
        $row['manual_crimping_2tons_with_gomusen'] ??'',
        $row['manual_crimping_2tons_normal_single_crimp'] ??'',
        $row['manual_crimping_2tons_normal_double_crimp'] ??'',
        $row['manual_crimping_2tons_to_be_joint_on_sw'] ??'',
        $row['manual_crimping_2tons_nsc_weld'] ??'',
        $row['manual_crimping_4tons_normal_terminal'] ??'',
        $row['manual_crimping_4tons_la_terminal'] ??'',
        $row['manual_crimping_nf_f'] ??'',
        $row['manual_crimping_5tons'] ??'',
        $row['intermediate_ripping_uas_manual_nf_f'] ??'',
        $row['intermediate_ripping_uas_joint'] ??'',
        $row['intermediate_stripping_kb10'] ??'',
        $row['intermediate_stripping_kb10_nsc_weld'] ??'',
        $row['joint_crimping_2tons_ps_800'] ??'',
        $row['joint_crimping_2tons_ps_700'] ??'',
        $row['joint_crimping_2tons_ps_017_126'] ??'',
        $row['joint_crimping_2tons_nsc_weld'] ??'',
        $row['joint_crimping_4tons_ps_200'] ??'',
        $row['joint_crimping_5tons'] ??'',
        $row['manual_taping_dispenser'] ??'',
        $row['joint_taping_11mm'] ??'',
        $row['joint_taping_12mm'] ??'',
        $row['joint_taping_13mm'] ??'',
        $row['joint_taping_13mm_nsc_weld'] ??'',
        $row['intermediate_welding_electrode_1'] ??'',
        $row['intermediate_welding_electrode_2'] ??'',
        $row['intermediate_welding_electrode_3'] ??'',
        $row['intermediate_welding_electrode_4'] ??'',
        $row['intermediate_welding_electrode_5'] ??'',
        $row['intermediate_welding_0_13_electrode_1'] ??'',
        $row['intermediate_welding_0_13_electrode_2'] ??'',
        $row['welding_at_head_electrode_1'] ??'',
        $row['welding_at_head_electrode_2'] ??'',
        $row['welding_at_head_electrode_3'] ??'',
        $row['welding_at_head_electrode_4'] ??'',
        $row['welding_at_head_electrode_5'] ??'',
        $row['welding_at_head_0_13_electrode_1'] ??'',
        $row['welding_at_head_0_13_electrode_2'] ??'',
        $row['silicon_injection'] ??'',
        $row['welding_cap_insertion'] ??'',
        $row['welding_taping_13mm'] ??'',
        $row['hs_components_insertion'] ??'',
        $row['heat_shrink_la_terminal'] ??'',
        $row['heat_shrink_joint_crimping'] ??'',
        $row['heat_shrink_welding'] ??'',
        $row['casting_c385'] ??'',
        $row['stmac_shieldwire_nissan'] ??'',
        $row['quick_stripping_927_auto'] ??'',
        $row['quick_stripping_311_manual'] ??'',
        $row['manual_heat_shrink_blower_sumitube'] ??'',
        $row['drainwire_tip'] ??'',
        $row['manual_crimping_shieldwire_2t'] ??'',
        $row['manual_crimping_shieldwire_4t'] ??'',
        $row['joint_crimping_2tons_ps_800_s_2_sw'] ??'',
        $row['joint_crimping_2tons_ps_017_ss_2_sw'] ??'',
        $row['manual_blue_taping_dispenser_sw'] ??'',
        $row['shieldwire_taping'] ??'',
        $row['hs_components_insertion_sw'] ??'',
        $row['heat_shrink_joint_crimping_sw'] ??'',
        $row['waterproof_pad_press_joint'] ??'',
        $row['waterproof_pad_press_weld'] ??'',
        $row['low_viscosity'] ??'',
        $row['air_water_leak_test'] ??'',
        $row['hirose_sheath_stripping_927r'] ??'',
        $row['hirose_unistrip'] ??'',
        $row['hirose_acetate_taping'] ??'',
        $row['hirose_manual_crimping_2_tons'] ??'',
        $row['hirose_copper_taping'] ??'',
        $row['hirose_hgt17ap_crimping'] ??'',
        $row['casting_c373'] ??'',
        $row['casting_c377'] ??'',
        $row['casting_c371'] ??'',
        $row['stmac_aluminum'] ??'',
        $row['manual_crimping_20tons'] ??'',
        $row['manual_heat_shrink_blower_battery'] ??'',
        $row['joint_crimping_20tons'] ??'',
        $row['dip_soldering_battery'] ??'',
        $row['ultrasonic_dip_soldering_aluminum'] ??'',
        $row['la_molding'] ??'',
        $row['air_water_leak_test_2'] ??'',
        $row['pressure_welding_dome_lamp'] ??'',
        $row['ferrule_casting_c373'] ??'',
        $row['ferrule_parts_insertion'] ??'',
        $row['ferrule_braided_wire_folding'] ??'',
        $row['outside_ferrule_insertion'] ??'',
        $row['ferrule_manual_crimping_2t'] ??'',
        $row['ferrule_crimping'] ??'',
        $row['ferrule_joint_crimping_2t'] ??'',
        $row['ferrule_welding_at_head'] ??'',
        $row['ferrule_welding_taping'] ??'',
        $row['gomusen_insertion'] ??'',
        $row['point_marking'] ??''
    ]);
}

fclose($output);
exit;
?>
